name: FlatRedBall

on:
  push:
    branches: [ "NetStandard" ]
  pull_request:
    branches: [ "NetStandard" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout FRB
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: 'FRB'

    - name: Checkout Gum
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/Gum
        fetch-depth: 1
        path: 'Gum'

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: dotnet build -c ${{ matrix.configuration }} 'FRB\FRBDK\Glue\Glue with All.sln'

    - name: Prepare package
      run: |
        mkdir _pack
        move FRB/FRBDK/Glue/Glue/bin/${{ matrix.configuration }} _pack/Glue
        move Gum/Gum/bin/${{ matrix.configuration }}/Data _pack/Gum
        echo 'start "" "Glue/Glue.exe"' > '_pack/Run FlatRedBall.bat'

    - name: Package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.configuration }}
        path: _pack
